In [19]:
%config Completer.use_jedi = False

# Iris Dataset

In [29]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import numpy as np

In [21]:
iris = load_iris(as_frame=True)

In [22]:
list(iris)

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [23]:
iris.data.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [24]:
iris.target.head(5)

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [25]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [26]:
X_iris = iris.data[["petal length (cm)", "petal width (cm)"]].values

In [27]:
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifier()

DecisionTreeClassifier()

# Testing Arrays and NumPy Functions

In [31]:
np.random.choice(10, 10, replace=False)

array([7, 6, 4, 5, 0, 2, 3, 8, 1, 9])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
X = np.random.choice(20, (4, 4), replace=False)

In [40]:
X

array([[ 2, 15, 12,  7],
       [ 0, 17,  1, 14],
       [13, 19,  9,  8],
       [11, 10, 18,  3]])

In [41]:
X[:]

array([[ 2, 15, 12,  7],
       [ 0, 17,  1, 14],
       [13, 19,  9,  8],
       [11, 10, 18,  3]])

In [42]:
X[:,]

array([[ 2, 15, 12,  7],
       [ 0, 17,  1, 14],
       [13, 19,  9,  8],
       [11, 10, 18,  3]])

In [53]:
X[:, 1]

array([15, 17, 19, 10])

In [54]:
X_column = X[:, 1]

# Np.Flatten

will collapse any x-d array to 1-d array

# Np.argwhere

will find the indices of what you pass into it(conditions)

# Np.Bincount

will find the occurances of non-negative integers in an array


In [55]:
print(X_column)

[15 17 19 10]


In [58]:
np.argwhere(X_column < 15).flatten()

array([3])

In [59]:
np.bincount(X_column)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1])